version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  centrifugo:
    image: centrifugo/centrifugo:v5
    volumes:
      - ./config/centrifugo.json:/centrifugo/config.json
    command: centrifugo -c /centrifugo/config.json
    ports:
      - 8001:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    restart: always
    depends_on:
      - redis
